INSERT INTO ROLE (ROLE_NAME) VALUES ('ADMIN');
INSERT INTO USER (USERNAME, PASSWORD) VALUES ('admin', '$2a$10$i1LZmQ9KAotvHgwsNV6mN.Zd0AikhB.L642OUu7PTGjT2Fzcdzdwu');
INSERT INTO USER_ROLES (USER_ID, ROLE_ID) VALUES (1,1);
INSERT INTO EMPLOYEE (FIRST_NAME, LAST_NAME, EMAIL) VALUES ('SRIHITA','MATURU', 'a@b.c');